### ISSUE TITLE
Doesn't change storefront if it's disabled on Playnite

### ISSUE THREAD

**Issue by MohandL3G** [kvdrrrrr/Playnite.StoreSpoofer#2]
Today I tried to change Stardew Valley storefront to GOG, but it didn't work, I didn't know why, I even restarted Playnite as Admin.

But after a little while, I tried to enable GOG extension from Settings > Extensions > GOG Library Importer.

I don't think that this is an issue, but I hope that you can write this on the description, so no one else have a bad experience as I did.

Sorry for bad English, and Thank you so much for this Plugin 😁

**Comment by illnyang** [comment]
already mentioned in #1. might update `README.md` later
